version: '2'
tasks:
  debug:
    cmds:
      - bash ./cmd/debug.sh
    sources:
      - ./app/**/*.go
  live-reload:
    cmds:
      - ps -ef | grep go-build | grep -v grep | awk '{print $2}' | xargs -r kill
      - go run main.go
    sources:
      - config/*.go
      - services/*.go
      - api/*.go
      - main.go